// Bidirectional L0 conformance check (NEYN-12044, snapchain#917).
//
// This is the external-client side of the golden corpus generated by snapchain
// (tests/conformance_test.rs). It proves that an independent implementation — here the Farcaster
// TS stack (@farcaster/core) — interoperates with snapchain's byte-exact crypto-layer output for every
// vector.
//
// IMPORTANT — what "byte-exact" means across clients:
// Protobuf serialization is NOT canonical across implementations (prost vs ts-proto differ on,
// e.g., empty `repeated` fields), so a client cannot reproduce snapchain's encoding from the
// semantic fields. The Farcaster spec (SPECIFICATION.md §2 Hashing) handles this with the
// `data_bytes` field: the hash/signature are computed over a carried serialization. Every corpus
// message carries `data_bytes` = snapchain's (prost) MessageData encoding. A conforming client
// therefore verifies the hash/signature against the CARRIED `data_bytes`, and must be able to
// decode both the wire `Message` and that `data_bytes` back into a `MessageData`. We deliberately
// do NOT assert that re-encoding reproduces the wire bytes — that is impossible across encoders and
// is exactly why `data_bytes` exists.
//
// State roots (the state-root layer) are not checked here: @farcaster/core has no merkle trie, and snapchain's
// sharded trie diverges from the (stale) trie spec in farcasterxyz/protocol §4.2. That layer is
// covered by the Rust cross-node test and tracked for reconciliation on epic NEYN-12026.

import * as fs from 'fs';
import * as path from 'path';
import { createPublicKey, verify as cryptoVerify } from 'crypto';
import { Message, MessageData } from '@farcaster/core';
import { blake3 } from '@noble/hashes/blake3';

const CORPUS_DIR = path.join(__dirname, '..', 'conformance', 'corpus', 'v1');

interface Expected {
  data_bytes: string;
  hash: string;
  signature: string;
  signer: string;
  message_bytes: string;
}

interface Vector {
  id: string;
  message_type: string;
  fid: number;
  timestamp: number;
  message_file: string;
  expected: Expected;
}

interface Corpus {
  corpus_version: number;
  protocol: { network: string; engine_version: string };
  vectors: Vector[];
}

function loadCorpus(): Corpus {
  const manifestPath = path.join(CORPUS_DIR, 'manifest.json');
  return JSON.parse(fs.readFileSync(manifestPath, 'utf8')) as Corpus;
}

const toHex = (bytes: Uint8Array): string => Buffer.from(bytes).toString('hex');

// snapchain hashes the serialized MessageData with BLAKE3 truncated to 20 bytes (160 bits).
function blake3Hash20(input: Uint8Array): Uint8Array {
  return blake3(input, { dkLen: 32 }).slice(0, 20);
}

// Pure Ed25519 verification over (message, signature, raw 32-byte public key) using Node's native
// crypto — independent of @farcaster/core, and avoids body-level validation that would reject the
// verification/key vectors whose envelope crypto is nonetheless valid. A raw Ed25519 public key is
// wrapped in its fixed SPKI DER prefix to build a KeyObject.
const ED25519_SPKI_PREFIX = Buffer.from('302a300506032b6570032100', 'hex');
function verifyEd25519(signature: Uint8Array, message: Uint8Array, publicKey: Uint8Array): boolean {
  const keyObject = createPublicKey({
    key: Buffer.concat([ED25519_SPKI_PREFIX, Buffer.from(publicKey)]),
    format: 'der',
    type: 'spki',
  });
  return cryptoVerify(null, Buffer.from(message), keyObject, Buffer.from(signature));
}

describe('L0 conformance corpus (bidirectional, crypto layer)', () => {
  const corpus = loadCorpus();

  test('corpus loads', () => {
    expect(corpus.vectors.length).toBeGreaterThan(0);
  });

  test.each(corpus.vectors.map((v) => [v.id, v]))('%s: crypto-layer cross-client parity', (_id, vector: Vector) => {
    const { expected, message_file } = vector;

    // The .pb on disk equals expected.message_bytes (corpus integrity).
    const pb = new Uint8Array(fs.readFileSync(path.join(CORPUS_DIR, message_file)));
    expect(toHex(pb)).toBe(expected.message_bytes);

    // The TS client can decode snapchain's wire Message (wire-format interop).
    const message = Message.decode(pb);
    expect(message.dataBytes).toBeDefined();
    expect(message.dataBytes!.length).toBeGreaterThan(0);

    // The carried canonical pre-image matches the manifest, and the hash is over it.
    expect(toHex(message.dataBytes!)).toBe(expected.data_bytes);
    const recomputed = blake3Hash20(message.dataBytes!);
    expect(toHex(recomputed)).toBe(expected.hash);
    expect(toHex(message.hash)).toBe(expected.hash);

    // The Ed25519 signature verifies over the hash; signature/signer bytes match.
    expect(toHex(message.signature)).toBe(expected.signature);
    expect(toHex(message.signer)).toBe(expected.signer);
    expect(verifyEd25519(message.signature, message.hash, message.signer)).toBe(true);

    // The pre-image decodes back into a MessageData with the expected semantic fields, proving the
    // TS client reads snapchain's prost-encoded payload consistently.
    const data = MessageData.decode(message.dataBytes!);
    expect(data.fid).toBe(vector.fid);
    expect(data.timestamp).toBe(vector.timestamp);
  });
});
