{
 "title": "Snapchain",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Snapchain Lag (in seconds)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=stats.gauges.snapchain.engine.block_delay_seconds')"
    }
   ]
  },
  {
   "title": "Block Production Rate (Target: 1)",
   "type": "stat",
   "description": "Rate at which blocks are being produced.\nNormally, it should be 1.\nIt can be higher than 1 when syncing\nIf it's lower than 1, then the node is having issue keeping up",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(seriesByTag('name=stats.gauges.snapchain.engine.block_height'))"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.gauges.snapchain.engine.block_height')"
    }
   ]
  },
  {
   "title": "Message Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "target": "perSecond(seriesByTag('name=stats.gauges.snapchain.engine.trie.num_items'))"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "stats.gauges.*.*.connected_peers"
    }
   ]
  },
  {
   "title": "Block Processing Time (p90 ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.timers.snapchain.engine.replay_proposal_time.upper_90')"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Transactions per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.snapchain.engine.commit.transactions')"
    }
   ]
  },
  {
   "title": "System Messages per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.snapchain.engine.commit.system_messages')"
    }
   ]
  },
  {
   "title": "User Messages per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.snapchain.engine.commit.user_messages')"
    }
   ]
  }
 ]
}