stats_calculation_interval = "2s"
num_iterations = 120

[submit_message]
rpc_addrs = [
    "http://127.0.0.11:3383",
    "http://127.0.0.12:3383",
    "http://127.0.0.13:3383"
]
interval = "2500us"

[follow_blocks]
rpc_addr = "http://127.0.0.11:3383"
enable = true