stats_calculation_interval = "2s"
num_iterations = 0

[submit_message]
rpc_addrs = [
        "http://10.0.1.18:13383",
        "http://10.0.0.63:13383",
        "http://10.0.2.97:13383",
        "http://10.0.1.144:13383",
]
interval = "10ms"

[follow_blocks]
rpc_addr = "http://10.0.1.18:13383"
enable = true
