[package]
name = "snapchain-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
prost = "0.13.3"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tonic-build = "0.9.2"
