name: Verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 20
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=64cpu-linux-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Build via Docker Compose
        run: docker compose build

  test:
    timeout-minutes: 20
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=64cpu-linux-arm64
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - uses: actions/checkout@v4
        with:
          repository: CassOnMars/eth-signature-verifier
          path: ./eth-signature-verifier

      - uses: actions/checkout@v4
        with:
          path: ./snapchain

      - working-directory: ./snapchain
        env:
          RUSTFLAGS: "-Dwarnings"
        run: cargo test

      - working-directory: ./snapchain
        env:
          RUSTFLAGS: "-Dwarnings"
        run: cargo build --bins

      - working-directory: ./snapchain
        env:
          RUSTFLAGS: "-Dwarnings"
        run: cargo fmt --all --check
